export const CHALLENGE_STATES = {
  PENDING_ACCEPTANCE: 'PENDING_ACCEPTANCE',
  ACCEPTED: 'ACCEPTED',
  LIVE: 'LIVE',
  CONFLICT: 'CONFLICT',
  COMPLETED: 'COMPLETED',
  SETTLED: 'SETTLED',
  CANCELLED: 'CANCELLED',
  REJECTED: 'REJECTED',
  REFUNDED: 'REFUNDED'
} as const;

export const FRIENDSHIP_STATUS = {
  PENDING: 'PENDING',
  ACCEPTED: 'ACCEPTED',
  REJECTED: 'REJECTED',
  BLOCKED: 'BLOCKED'
} as const;

export const TRANSACTION_TYPES = {
  DEPOSIT: 'DEPOSIT',
  WITHDRAWAL: 'WITHDRAWAL',
  STAKE_DEBIT: 'STAKE_DEBIT',
  STAKE_REFUND: 'STAKE_REFUND',
  WINNING_CREDIT: 'WINNING_CREDIT',
  PLATFORM_FEE: 'PLATFORM_FEE',
  WITNESS_REWARD: 'WITNESS_REWARD'
} as const;

export const TRANSACTION_STATUS = {
  PENDING: 'PENDING',
  COMPLETED: 'COMPLETED',
  FAILED: 'FAILED',
  REVERSED: 'REVERSED'
} as const;

export const NOTIFICATION_TYPES = {
  FRIEND_REQUEST: 'FRIEND_REQUEST',
  FRIEND_ACCEPTED: 'FRIEND_ACCEPTED',
  CHALLENGE_RECEIVED: 'CHALLENGE_RECEIVED',
  CHALLENGE_ACCEPTED: 'CHALLENGE_ACCEPTED',
  CHALLENGE_REJECTED: 'CHALLENGE_REJECTED',
  CHALLENGE_STARTING_SOON: 'CHALLENGE_STARTING_SOON',
  CHALLENGE_LIVE: 'CHALLENGE_LIVE',
  CHALLENGE_COMPLETED: 'CHALLENGE_COMPLETED',
  CHALLENGE_SETTLED: 'CHALLENGE_SETTLED',
  WALLET_FUNDED: 'WALLET_FUNDED',
  PAYOUT_RECEIVED: 'PAYOUT_RECEIVED',
  WITNESS_REQUEST: 'WITNESS_REQUEST'
} as const;

export const GAMES = {
  EFOOTBALL: 'EFOOTBALL'
} as const;

export const PLATFORMS = {
  MOBILE: 'MOBILE',
  CONSOLE: 'CONSOLE'
} as const;

export const CHALLENGE_TYPES = {
  FRIENDS: 'FRIENDS',
  DIRECT: 'DIRECT',
  PUBLIC: 'PUBLIC'
} as const;

export const SETTLEMENT_METHODS = {
  PLATFORM: 'PLATFORM',
  WITNESS: 'WITNESS'
} as const;

export const WITNESS_STATUS = {
  PENDING_WITNESS_ACCEPTANCE: 'PENDING_WITNESS_ACCEPTANCE',
  WITNESS_ACCEPTED: 'WITNESS_ACCEPTED',
  WITNESS_DECLINED: 'WITNESS_DECLINED'
} as const;

export const CURRENCIES = {
  NGN: 'NGN',
  USD: 'USD',
  EUR: 'EUR',
  GBP: 'GBP'
} as const;

export type ChallengeState = (typeof CHALLENGE_STATES)[keyof typeof CHALLENGE_STATES];
export type FriendshipStatus = (typeof FRIENDSHIP_STATUS)[keyof typeof FRIENDSHIP_STATUS];
export type TransactionType = (typeof TRANSACTION_TYPES)[keyof typeof TRANSACTION_TYPES];
export type TransactionStatus = (typeof TRANSACTION_STATUS)[keyof typeof TRANSACTION_STATUS];
export type NotificationType = (typeof NOTIFICATION_TYPES)[keyof typeof NOTIFICATION_TYPES];
export type Game = (typeof GAMES)[keyof typeof GAMES];
export type Platform = (typeof PLATFORMS)[keyof typeof PLATFORMS];
export type ChallengeType = (typeof CHALLENGE_TYPES)[keyof typeof CHALLENGE_TYPES];
export type SettlementMethod = (typeof SETTLEMENT_METHODS)[keyof typeof SETTLEMENT_METHODS];
export type WitnessStatus = (typeof WITNESS_STATUS)[keyof typeof WITNESS_STATUS];
export type Currency = (typeof CURRENCIES)[keyof typeof CURRENCIES];
